name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run sitespeed.io
        uses: docker://sitespeedio/sitespeed.io:latest
        with:
          args: https://e28c-188-169-60-169.ngrok-free.app --budget.configPath ./homeBudget.json

      - name: Upload sitespeed.io results
        uses: actions/upload-artifact@v4
        with:
          name: sitespeed-results
          path: ./sitespeed-result
